# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

  display:
    runs-on: self-hosted
    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PORT: ${{ secrets.PORT }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
        CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
        CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        GMAIL: ${{ secrets.GMAIL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SMTP_GMAIL: ${{ secrets.SMTP_GMAIL }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo "Database ${{ secrets.DATABASE_URL }}"
    - run: npm i
    - run: npm run build --if-present
    - run: npm start
